version: '2.0'
services:

  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meldingen
      POSTGRES_USER: meldingen
      POSTGRES_PASSWORD: insecure

  api:
    build: ./api
    ports:
      - "8001:8001"
    links:
      - database
    environment:
      - DB_NAME=meldingen
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/signals/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=meldingen.wsgi:application
